npm install --save-dev grunt-contrib-copy
npm install --save-dev grunt-contrib-less
npm install --save-dev grunt-contrib-csslint
npm install --save-dev grunt-preprocess
npm install --save-dev grunt-jslint
npm install --save-dev grunt-contrib-jasmine
npm install --save-dev grunt-contrib-uglify
npm install --save-dev grunt-contrib-clean
npm install --save-dev grunt-contrib-imagemin
npm install --save-dev grunt-newer
npm install --save-dev imagemin-mozjpeg
